<a href="https://colab.research.google.com/github/Ugot-Aaron-Paul/58013-LinearAlgebra/blob/main/Lab_9_MATRIX_ALGEBRA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

*Associative*

In [1]:
import numpy as np
A = np.array([[1,2,3],[9,1,1],[4,2,0]])
B = np.array([[7,6,9],[1,1,1],[6,6,6]])
C = np.array([[1,2,3],[5,6,7],[1,5,0]])

Result1 = np.dot(np.dot(A,B),C)
Result2 = np.dot(A,np.dot(B,C))

print("Result 1 is:\n",Result1)

print("Result 2 is:\n",Result2)

Result 1 is:
 [[186 355 263]
 [463 946 637]
 [198 406 272]]
Result 2 is:
 [[186 355 263]
 [463 946 637]
 [198 406 272]]


*Distributive*

In [2]:
import numpy as np
A = np.array([[1,2,3],[9,1,1],[4,2,0]])
B = np.array([[7,6,9],[1,1,1],[6,6,6]])
C = np.array([[1,2,3],[5,6,7],[1,5,0]])

Result1 = np.dot(A, B + C)

Result2 = np.dot(A, B) + np.dot(A, C)

print("Result 1 is:\n",Result1)

print("Result 2 is:\n",Result2)

Result 1 is:
 [[ 41  55  46]
 [ 85  90 122]
 [ 44  46  64]]
Result 2 is:
 [[ 41  55  46]
 [ 85  90 122]
 [ 44  46  64]]


*Identity*

In [4]:
import numpy as np
A = np.array([[1,2,3],[9,1,1],[4,2,0]])
B = np.array([[7,6,9],[1,1,1],[6,6,6]])
C = np.array([[1,2,3],[5,6,7],[1,5,0]])

I = np.identity(3)

Result1 = np.dot(A, I)

Result2 = A

print("Result 1 is:\n",Result1)

print("Result 2 is:\n",Result2)

Result 1 is:
 [[1. 2. 3.]
 [9. 1. 1.]
 [4. 2. 0.]]
Result 2 is:
 [[1 2 3]
 [9 1 1]
 [4 2 0]]


*Zero*

In [5]:
import numpy as np
A = np.array([[1,2,3],[9,1,1],[4,2,0]])
B = np.array([[7,6,9],[1,1,1],[6,6,6]])
C = np.array([[1,2,3],[5,6,7],[1,5,0]])

zero_matrix = np.zeros_like(A)

Result1 = np.dot(A, zero_matrix)

Result2 = zero_matrix

print("Result 1 is:\n",Result1)

print("Result 2 is:\n",Result2)

Result 1 is:
 [[0 0 0]
 [0 0 0]
 [0 0 0]]
Result 2 is:
 [[0 0 0]
 [0 0 0]
 [0 0 0]]


*Scalar*

In [6]:
import numpy as np
A = np.array([[1,2,3],[9,1,1],[4,2,0]])
B = np.array([[7,6,9],[1,1,1],[6,6,6]])
C = np.array([[1,2,3],[5,6,7],[1,5,0]])

k = 2

Result1 = np.dot(k * A, B)

Result2 = k * np.dot(A, B)

print("Result 1 is:\n",Result1)

print("Result 2 is:\n",Result2)

Result 1 is:
 [[ 54  52  58]
 [140 122 176]
 [ 60  52  76]]
Result 2 is:
 [[ 54  52  58]
 [140 122 176]
 [ 60  52  76]]


*Closure*

In [7]:
import numpy as np
A = np.array([[1,2,3],[9,1,1],[4,2,0]])
B = np.array([[7,6,9],[1,1,1],[6,6,6]])
C = np.array([[1,2,3],[5,6,7],[1,5,0]])

Result1 = np.dot(A, B)
Result2 = np.dot(B, C)

print("Result 1 is:\n",Result1)

print("Result 2 is:\n",Result2)

Result 1 is:
 [[27 26 29]
 [70 61 88]
 [30 26 38]]
Result 2 is:
 [[46 95 63]
 [ 7 13 10]
 [42 78 60]]
