<a href="https://colab.research.google.com/github/Ugot-Aaron-Paul/58013-LinearAlgebra/blob/main/Long%20Quiz%201.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [39]:
import numpy as np

A = np.array([[1,2,3],[4,5,6]])
B = np.array([[1,2],[3,4],[5,6]])
C = np.array([[1,2,3],[4,5,6],[7,8,9]])
D = np.array([[1,2],[3,4]])

print("Given matrices are:")

print("A:\n",A)

print("B:\n", B)

print("C:\n", C)

print("D:\n", D)

a = np.dot(A,B)
b = np.add(D,D)
c = 2*C

print("\nQuestions:")

print("a)AB:\n",a)

print("\nb)D+D:\n",b)

print("\nc)2C:\n",c)

Given matrices are:
A:
 [[1 2 3]
 [4 5 6]]
B:
 [[1 2]
 [3 4]
 [5 6]]
C:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
D:
 [[1 2]
 [3 4]]

Questions:
a)AB:
 [[22 28]
 [49 64]]

b)D+D:
 [[2 4]
 [6 8]]

c)2C:
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [45]:
import numpy as np

A = np.array([2, 7, 4])
B = np.array([3, 9, 8])

ans = [(A[1]*B[2])-(A[2]*B[1]), (A[2]*B[0])-(A[0]*B[2]),(A[0]*B[1])-(A[1]*B[0])]

print("The Cross product of A and B is:", ans)

The Cross product of A and B is: [20, -4, -3]
