<a href="https://colab.research.google.com/github/Ugot-Aaron-Paul/58013-LinearAlgebra/blob/main/Prelim%20Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Question 1

In [6]:
import numpy as np

def table(x):
    num = np.arange(1, x+1)
    return num * num[:, None]

print(table(10))

[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


Question 2

In [1]:
import numpy as np

def table(x):
    num = np.arange(1, x+1)
    return num * 2 * num[:, None]

print(table(10))

[[  2   4   6   8  10  12  14  16  18  20]
 [  4   8  12  16  20  24  28  32  36  40]
 [  6  12  18  24  30  36  42  48  54  60]
 [  8  16  24  32  40  48  56  64  72  80]
 [ 10  20  30  40  50  60  70  80  90 100]
 [ 12  24  36  48  60  72  84  96 108 120]
 [ 14  28  42  56  70  84  98 112 126 140]
 [ 16  32  48  64  80  96 112 128 144 160]
 [ 18  36  54  72  90 108 126 144 162 180]
 [ 20  40  60  80 100 120 140 160 180 200]]


Question 3

In [4]:
import numpy as np
SM = np.array([[1,0,0],[0,1,0],[0,0,1]])
print("square matrix that has a diagonal 1's:\n", SM)

square matrix that has a diagonal 1's:
 [[1 0 0]
 [0 1 0]
 [0 0 1]]


Question 4

In [5]:
import numpy as np

matrix = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

print("The Matrix is:\n", matrix)
Size = np.size(matrix)
Shape = np.shape(matrix)
Dimension = np.ndim(matrix)

print("\nThe Size of the matrix is:", Size, "\nThe Shape of the matrix is:", Shape, "\nThe Dimension of the matrix is:", Dimension)

The Matrix is:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

The Size of the matrix is: 12 
The Shape of the matrix is: (3, 4) 
The Dimension of the matrix is: 2


Question 5

In [17]:
import numpy as numpy
arrayOne = numpy.array([[5,6,9],[21,18,27]])
arrayTwo = numpy.array([[15,33,24],[4,7,1]])

print("Array 1 is:\n",arrayOne)
print("\nArray 2 is:\n",arrayTwo)
Result = numpy.add(arrayOne,arrayTwo)
print("\nHere is the Sum of Two Arrays:\n", Result)
Result ^=2
print("\nHere is the square of each element of the sum:\n", Result)

Array 1 is:
 [[ 5  6  9]
 [21 18 27]]

Array 2 is:
 [[15 33 24]
 [ 4  7  1]]

Here is the Sum of Two Arrays:
 [[20 39 33]
 [25 25 28]]

Here is the square of each element of the sum:
 [[22 37 35]
 [27 27 30]]
