<a href="https://colab.research.google.com/github/Ugot-Aaron-Paul/58013-LinearAlgebra/blob/main/Vector%2CSpaces%2Cand%20Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Vectors

In [7]:
import numpy as np

A = np.array([4,3])
B = np.array([2, -5])
print('Vector A is ', A)
print('Vector B is ', B)

Vector A is  [4 3]
Vector B is  [ 2 -5]


Shape of the Matrix

In [20]:
ball1 = np.array([1,2,3])
ball2 = np.array([0,1,-1])
ball = np.shape(ball1) + np.shape(ball2)
print(ball)
balls = np.ndim(ball1), np.ndim(ball2)
print(balls)

(3, 3)
(1, 1)


Addition

In [21]:
R1 = np.array([4,3])
R2 = np.array([2,-5])

R = np.add(R1,R2)
print(R)

[ 6 -2]


Subtraction

In [22]:
R1 = np.array([4,3])
R2 = np.array([2,-5])

R = np.subtract(R1,R2)
print(R)

[2 8]


Scalar Product

In [23]:
R = np.array([2])
V = R*A
print(V)

[8 6]


Dot Product

In [24]:
R1 = np.array([4,3])
R2 = np.array([2,-5])

R = np.dot(R1,R2)
print(R)

-7


Matrix Property

In [27]:
#Identity Matrix
c = np.eye(3,3)
print(c)

#Zero Matrix
d = np.zeros([5,5])
print(d)

#Null Matrix
e = np.full((3,3),7)
print(e)

#Transpose Matrix
f = np.transpose(A)
print(f)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[7 7 7]
 [7 7 7]
 [7 7 7]]
[4 3]
